/**
 * 3D Spatial Telemetry Hubs & Places Data
 * Exact geographic coordinates, corridors, facilities, and live disruption statuses
 * for Indian logistics networks in SupplyChain Guardian.
 */

export const SPATIAL_PLACES = [
  {
    id: 'PUNE',
    code: 'PUN',
    name: 'Pune Chakan Hub',
    city: 'Pune',
    state: 'Maharashtra',
    lat: 18.5204,
    lng: 73.8567,
    x: -35,
    y: 15,
    z: 25,
    type: 'PRIMARY_SUPPLIER_CLUSTER',
    tier: 'Tier-1 Automotive Microcontrollers',
    facilities: ['Tata AutoComp Systems Ltd', 'Kalyani Forge Hub'],
    corridors: ['NH-48 Pune-Mumbai Expressway', 'Pune-Bengaluru Highway'],
    nominalRisk: 'LOW',
    disruptedRisk: 'CRITICAL',
    disruptedReason: 'Flash flood & 220kV substation power loss at Chakan. 100% assembly stopped.',
    nominalReason: 'Operating at standard 85,000 units/mo fabrication capacity.',
    inventoryValue: '₹14.2 Cr',
    capacityUtilization: '88%',
    bufferDays: '1.8 Days (Critical Breach Risk)',
    activeShipments: 4,
    color: '#f43f5e',
    nominalColor: '#06b6d4',
    description: 'Primary fab foundries for automotive ECUs supplying Maruti Suzuki, Mahindra & Ather Energy.',
  },
  {
    id: 'BLR',
    code: 'BLR',
    name: 'Bengaluru Silicon Corridor',
    city: 'Bengaluru',
    state: 'Karnataka',
    lat: 12.9716,
    lng: 77.5946,
    x: 15,
    y: 80,
    z: -25,
    type: 'HIGH_TECH_FOUNDRY_PARK',
    tier: 'Tier-1 Alternative Semiconductor Foundry',
    facilities: ['Bharat Silicon & Foundry Ltd', 'Southern Tech Logistics Park WH-02'],
    corridors: ['Air Cargo BLR-BOM Flight BDA-91', 'NH-44 South Transit Spine'],
    nominalRisk: 'OPTIMAL',
    disruptedRisk: 'OPTIMAL',
    disruptedReason: 'Option B candidate: 28,000 emergency MCU units verified and ready for air cargo dispatch.',
    nominalReason: '97.2% reliability rating with 65,000 units/mo capacity.',
    inventoryValue: '₹22.5 Cr',
    capacityUtilization: '74%',
    bufferDays: '12.0 Days (Safe)',
    activeShipments: 6,
    color: '#10b981',
    nominalColor: '#10b981',
    description: 'Premier Indian semiconductor foundry and primary backup supplier for autonomous recovery (Option B).',
  },
  {
    id: 'BOM',
    code: 'BOM',
    name: 'Bhiwandi Western Mega DC',
    city: 'Bhiwandi (Mumbai)',
    state: 'Maharashtra',
    lat: 19.2967,
    lng: 73.0631,
    x: -60,
    y: -5,
    z: 35,
    type: 'MEGA_DISTRIBUTION_CENTER',
    tier: 'Central Western Consolidation Hub',
    facilities: ['Western Hub Mega DC WH-01', 'JNPT Port Cargo Freight Depot'],
    corridors: ['NH-48 Western Freight Corridor', 'JNPT Maritime Gateway'],
    nominalRisk: 'LOW',
    disruptedRisk: 'AT_RISK',
    disruptedReason: 'Depot buffer dropping under 2 days due to zero inbound shipments from halted Pune fab.',
    nominalReason: '300,000 units capacity operating smoothly across 4 loading docks.',
    inventoryValue: '₹38.1 Cr',
    capacityUtilization: '82%',
    bufferDays: '2.1 Days (Declining Rapidly)',
    activeShipments: 8,
    color: '#38bdf8',
    nominalColor: '#38bdf8',
    description: 'Largest western mega distribution center feeding assembly plants across Maharashtra and Gujarat.',
  },
  {
    id: 'DEL',
    code: 'DEL',
    name: 'NCR Manesar Logistics Core',
    city: 'Manesar (Gurugram)',
    state: 'Haryana',
    lat: 28.3588,
    lng: 76.9388,
    x: -20,
    y: -110,
    z: -15,
    type: 'NORTHERN_DISTRIBUTION_HUB',
    tier: 'Northern Manufacturing Anchor',
    facilities: ['Northern NCR Distribution Hub WH-04', 'Maruti Suzuki Auto Cluster'],
    corridors: ['Delhi-Mumbai Industrial Corridor (DMIC)', 'Western Dedicated Freight Corridor'],
    nominalRisk: 'LOW',
    disruptedRisk: 'LOW',
    disruptedReason: 'Northern buffer holding steady; monitor connecting rail link for transit delays.',
    nominalReason: '250,000 units capacity running nominal schedules.',
    inventoryValue: '₹19.4 Cr',
    capacityUtilization: '72%',
    bufferDays: '9.5 Days (Safe)',
    activeShipments: 5,
    color: '#8b5cf6',
    nominalColor: '#8b5cf6',
    description: 'Northern logistics nexus anchoring 250,000 units capacity directly linked to Delhi-Mumbai freight lines.',
  },
  {
    id: 'MAA',
    code: 'MAA',
    name: 'Chennai Sriperumbudur Corridor',
    city: 'Sriperumbudur (Chennai)',
    state: 'Tamil Nadu',
    lat: 12.9700,
    lng: 79.9400,
    x: 48,
    y: 85,
    z: 30,
    type: 'PRECISION_ELECTRONICS_DEPOT',
    tier: 'Tier-1 PCB Assembly & Deep Sea Port',
    facilities: ['Foxconn Precision Industrial Hub', 'Chennai Auto-Corridor Depot WH-03'],
    corridors: ['Chennai Port Maritime Highway', 'NH-48 South East Corridor'],
    nominalRisk: 'MODERATE',
    disruptedRisk: 'MODERATE',
    disruptedReason: 'Heavy monsoon cloud cover; container yard handling at 89% capacity.',
    nominalReason: '220,000 units capacity running standard PCB assembly pipelines.',
    inventoryValue: '₹26.8 Cr',
    capacityUtilization: '89%',
    bufferDays: '5.2 Days (Moderate)',
    activeShipments: 7,
    color: '#f59e0b',
    nominalColor: '#f59e0b',
    description: 'High-density electronics manufacturing ecosystem and southern maritime container gateway.',
  },
  {
    id: 'HYD',
    code: 'HYD',
    name: 'Hyderabad Shamshabad Hub',
    city: 'Hyderabad',
    state: 'Telangana',
    lat: 17.2403,
    lng: 78.4294,
    x: 15,
    y: 35,
    z: -10,
    type: 'AEROSPACE_CENTRAL_DEPOT',
    tier: 'Central Intermodal Crossroads',
    facilities: ['Deccan Aerospace & Electronics Depot WH-05', 'GMR Air Cargo Logistics Village'],
    corridors: ['NH-44 North-South Highway', 'Rajiv Gandhi Int. Airport Cargo Line'],
    nominalRisk: 'LOW',
    disruptedRisk: 'LOW',
    disruptedReason: 'Operating smoothly with zero reported delays; acts as transit cross-dock.',
    nominalReason: '180,000 units capacity with high freight throughput.',
    inventoryValue: '₹15.7 Cr',
    capacityUtilization: '61%',
    bufferDays: '11.4 Days (Safe)',
    activeShipments: 4,
    color: '#06b6d4',
    nominalColor: '#06b6d4',
    description: 'Central logistics crossroads connecting north, south, and western Indian freight corridors.',
  },
  {
    id: 'AMD',
    code: 'AMD',
    name: 'Ahmedabad Sanand Hub',
    city: 'Sanand (Ahmedabad)',
    state: 'Gujarat',
    lat: 23.0225,
    lng: 72.5714,
    x: -80,
    y: -45,
    z: 10,
    type: 'WESTERN_FOUNDRY_NODE',
    tier: 'EV Powertrain & Intermodal Hub',
    facilities: ['Sanand EV Motor Cluster', 'Gujarat Intermodal Logistics Yard'],
    corridors: ['NE-1 National Expressway', 'Mundra Port Dedicated Rail Corridor'],
    nominalRisk: 'LOW',
    disruptedRisk: 'LOW',
    disruptedReason: 'High EV motor component buffer with steady production schedules.',
    nominalReason: 'Operating at 68% utilization with 8.7 buffer days.',
    inventoryValue: '₹12.4 Cr',
    capacityUtilization: '68%',
    bufferDays: '8.7 Days (Safe)',
    activeShipments: 3,
    color: '#6366f1',
    nominalColor: '#6366f1',
    description: 'Western automotive corridor specializing in EV drivetrain and battery integration units.',
  },
];

// Connecting freight corridors between the places
export const SPATIAL_EDGES = [
  { from: 'PUNE', to: 'BOM', label: 'NH-48 Pune-Mumbai Expressway', distanceKm: 148 },
  { from: 'PUNE', to: 'BLR', label: 'Pune-Bengaluru Highway', distanceKm: 840 },
  { from: 'BLR', to: 'BOM', label: 'Air Cargo Flight VT-BDA-91', distanceKm: 980, isAir: true },
  { from: 'BLR', to: 'MAA', label: 'NH-48 Bengaluru-Chennai Spur', distanceKm: 345 },
  { from: 'BLR', to: 'HYD', label: 'NH-44 Hyderabad-Bengaluru Spine', distanceKm: 570 },
  { from: 'BOM', to: 'DEL', label: 'Delhi-Mumbai Western Freight Corridor', distanceKm: 1410 },
  { from: 'BOM', to: 'AMD', label: 'NH-48 Mumbai-Ahmedabad Corridor', distanceKm: 525 },
  { from: 'AMD', to: 'DEL', label: 'Gujarat-NCR Expressway', distanceKm: 920 },
  { from: 'HYD', to: 'DEL', label: 'North-South Central Freight Line', distanceKm: 1540 },
  { from: 'HYD', to: 'MAA', label: 'Deccan-Coromandel Corridor', distanceKm: 625 },
];
