/**
 * Comprehensive Realistic Seed Data for Supply Chain Guardian
 * Features realistic Indian manufacturing & logistics hubs, ₹ pricing, SLA tiers, and live routes.
 */

const bcrypt = require('bcryptjs');

// Hash for demo user password 'Password123!'
const DEMO_PASSWORD_HASH = bcrypt.hashSync('Password123!', 10);

const users = [
  {
    id: 'u-admin-01',
    email: 'admin@nexchain.ai',
    password_hash: DEMO_PASSWORD_HASH,
    full_name: 'Dr. Vikram Malhotra',
    role_id: 'ADMIN',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=256&q=80',
    is_active: true,
  },
  {
    id: 'u-supply-01',
    email: 'supply.manager@nexchain.ai',
    password_hash: DEMO_PASSWORD_HASH,
    full_name: 'Ananya Sharma',
    role_id: 'SUPPLY_MANAGER',
    avatar_url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=256&q=80',
    is_active: true,
  },
  {
    id: 'u-ops-01',
    email: 'ops.lead@nexchain.ai',
    password_hash: DEMO_PASSWORD_HASH,
    full_name: 'Rajesh Nair',
    role_id: 'OPERATIONS_MANAGER',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=256&q=80',
    is_active: true,
  },
  {
    id: 'u-view-01',
    email: 'viewer@nexchain.ai',
    password_hash: DEMO_PASSWORD_HASH,
    full_name: 'Priya Sundaram',
    role_id: 'VIEWER',
    avatar_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=256&q=80',
    is_active: true,
  },
];

const warehouses = [
  {
    id: 'wh-01',
    code: 'WH-BHIWANDI',
    name: 'Western Hub Mega DC',
    city: 'Bhiwandi (Mumbai)',
    state: 'Maharashtra',
    country: 'India',
    latitude: 19.2967,
    longitude: 73.0631,
    total_capacity_units: 300000,
    utilized_capacity_units: 245000,
    operational_status: 'OPERATIONAL',
    contact_phone: '+91 22 4589 1101',
  },
  {
    id: 'wh-02',
    code: 'WH-WHITEFIELD',
    name: 'Southern Tech Logistics Park',
    city: 'Bengaluru',
    state: 'Karnataka',
    country: 'India',
    latitude: 12.9698,
    longitude: 77.7500,
    total_capacity_units: 200000,
    utilized_capacity_units: 162000,
    operational_status: 'OPERATIONAL',
    contact_phone: '+91 80 6620 4400',
  },
  {
    id: 'wh-03',
    code: 'WH-SRIPERUMBUDUR',
    name: 'Chennai Auto-Corridor Depot',
    city: 'Sriperumbudur',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 12.9700,
    longitude: 79.9400,
    total_capacity_units: 220000,
    utilized_capacity_units: 195000,
    operational_status: 'CONGESTED',
    contact_phone: '+91 44 2716 8800',
  },
  {
    id: 'wh-04',
    code: 'WH-MANESAR',
    name: 'Northern NCR Distribution Hub',
    city: 'Manesar (Gurugram)',
    state: 'Haryana',
    country: 'India',
    latitude: 28.3588,
    longitude: 76.9388,
    total_capacity_units: 250000,
    utilized_capacity_units: 180000,
    operational_status: 'OPERATIONAL',
    contact_phone: '+91 124 492 3300',
  },
  {
    id: 'wh-05',
    code: 'WH-SHAMSHABAD',
    name: 'Deccan Aerospace & Electronics Depot',
    city: 'Hyderabad',
    state: 'Telangana',
    country: 'India',
    latitude: 17.2403,
    longitude: 78.4294,
    total_capacity_units: 180000,
    utilized_capacity_units: 110000,
    operational_status: 'OPERATIONAL',
    contact_phone: '+91 40 2400 9900',
  },
];

const suppliers = [
  {
    id: 'sup-01',
    code: 'SUP-TATA-PUNE',
    name: 'Tata AutoComp Systems Ltd',
    tier: 'TIER_1',
    category: 'Automotive Microcontrollers',
    city: 'Pune',
    state: 'Maharashtra',
    country: 'India',
    latitude: 18.5204,
    longitude: 73.8567,
    reliability_score: 84.5,
    avg_lead_time_days: 4,
    capacity_units_per_month: 85000,
    cost_index: 1.00,
    status: 'CRITICAL_SHUTDOWN', // Target of demo disruption
    risk_level: 'CRITICAL',
    risk_factors: {
      delivery_risk: 94.0,
      geopolitical_risk: 15.0,
      financial_health_risk: 28.0,
      weather_climate_risk: 96.0,
      capacity_constraint_risk: 88.0,
      summary: 'Critical disruption: Chakan industrial flash flood & substation grid explosion. 100% assembly stopped.',
    },
    primary_contact: {
      name: 'Sandeep Deshpande',
      title: 'VP Supply Operations',
      email: 's.deshpande@tataautocomp.com',
      phone: '+91 98230 44551',
    },
  },
  {
    id: 'sup-02',
    code: 'SUP-BHARAT-BLR',
    name: 'Bharat Silicon & Foundry Ltd',
    tier: 'TIER_1',
    category: 'MCUs & Power MOSFETs',
    city: 'Bengaluru',
    state: 'Karnataka',
    country: 'India',
    latitude: 12.9716,
    longitude: 77.5946,
    reliability_score: 97.2,
    avg_lead_time_days: 5,
    capacity_units_per_month: 65000,
    cost_index: 1.07,
    status: 'ACTIVE',
    risk_level: 'LOW',
    risk_factors: {
      delivery_risk: 16.0,
      geopolitical_risk: 10.0,
      financial_health_risk: 18.0,
      weather_climate_risk: 14.0,
      capacity_constraint_risk: 32.0,
      summary: 'Optimal alternative supplier with available 28,000 unit buffer ready for immediate emergency contract allocation.',
    },
    primary_contact: {
      name: 'Dr. Kavitha Raman',
      title: 'Managing Director',
      email: 'kavitha@bharatsilicon.in',
      phone: '+91 98450 12890',
    },
  },
  {
    id: 'sup-03',
    code: 'SUP-FOXCONN-CHN',
    name: 'Foxconn Precision Industrial Hub',
    tier: 'TIER_1',
    category: 'High-Density PCB Assembly',
    city: 'Sriperumbudur',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 12.9800,
    longitude: 79.9500,
    reliability_score: 93.4,
    avg_lead_time_days: 6,
    capacity_units_per_month: 125000,
    cost_index: 1.04,
    status: 'ACTIVE',
    risk_level: 'MEDIUM',
    risk_factors: {
      delivery_risk: 38.0,
      geopolitical_risk: 22.0,
      financial_health_risk: 15.0,
      weather_climate_risk: 54.0,
      capacity_constraint_risk: 45.0,
      summary: 'Operating normally; slight port delay at Ennore port due to seasonal swells, managed via inland road freight.',
    },
    primary_contact: {
      name: 'K. Balasubramanian',
      title: 'Logistics Director',
      email: 'bala.k@foxconn-india.com',
      phone: '+91 98401 77234',
    },
  },
  {
    id: 'sup-04',
    code: 'SUP-VEDANTA-GUJ',
    name: 'Vedanta Semiconductor Dholera',
    tier: 'TIER_1',
    category: 'Silicon Wafers & Sensors',
    city: 'Dholera',
    state: 'Gujarat',
    country: 'India',
    latitude: 22.2472,
    longitude: 72.1969,
    reliability_score: 92.1,
    avg_lead_time_days: 7,
    capacity_units_per_month: 70000,
    cost_index: 0.98,
    status: 'ACTIVE',
    risk_level: 'LOW',
    risk_factors: {
      delivery_risk: 24.0,
      geopolitical_risk: 18.0,
      financial_health_risk: 20.0,
      weather_climate_risk: 12.0,
      capacity_constraint_risk: 38.0,
      summary: 'Stable operations with dedicated 50MW captive solar grid and zero weather alerts.',
    },
    primary_contact: {
      name: 'Nitin Patel',
      title: 'Head of Operations',
      email: 'n.patel@vedantasemicon.com',
      phone: '+91 98250 66120',
    },
  },
  {
    id: 'sup-05',
    code: 'SUP-MOTHER-NOI',
    name: 'Motherson Sumi Systems',
    tier: 'TIER_1',
    category: 'Automotive Wiring & Harnesses',
    city: 'Noida',
    state: 'Uttar Pradesh',
    country: 'India',
    latitude: 28.5355,
    longitude: 77.3910,
    reliability_score: 95.0,
    avg_lead_time_days: 4,
    capacity_units_per_month: 90000,
    cost_index: 1.02,
    status: 'ACTIVE',
    risk_level: 'LOW',
    risk_factors: {
      delivery_risk: 20.0,
      geopolitical_risk: 12.0,
      financial_health_risk: 16.0,
      weather_climate_risk: 18.0,
      capacity_constraint_risk: 28.0,
      summary: 'Consistent on-time delivery; robust automated inventory warehousing in NCR.',
    },
    primary_contact: {
      name: 'Alok Gupta',
      title: 'Senior GM Logistics',
      email: 'alok.g@motherson.com',
      phone: '+91 98110 33452',
    },
  },
  {
    id: 'sup-06',
    code: 'SUP-EXIDE-HOS',
    name: 'Exide Energy Solutions EV Cell',
    tier: 'TIER_1',
    category: 'Lithium-Ion EV Battery Packs',
    city: 'Hosur',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 12.7409,
    longitude: 77.8253,
    reliability_score: 88.6,
    avg_lead_time_days: 8,
    capacity_units_per_month: 40000,
    cost_index: 1.14,
    status: 'ACTIVE',
    risk_level: 'MEDIUM',
    risk_factors: {
      delivery_risk: 42.0,
      geopolitical_risk: 35.0,
      financial_health_risk: 25.0,
      weather_climate_risk: 22.0,
      capacity_constraint_risk: 56.0,
      summary: 'High demand pressure from domestic EV OEMs; cell supply constrained by global lithium import queues.',
    },
    primary_contact: {
      name: 'Ravi Teja',
      title: 'Cell Technology Operations',
      email: 'rteja@exideenergy.in',
      phone: '+91 97410 88201',
    },
  },
  {
    id: 'sup-07',
    code: 'SUP-LUMAX-GUR',
    name: 'Lumax Auto Technologies',
    tier: 'TIER_2',
    category: 'LED Lighting Modules & Sensors',
    city: 'Gurugram',
    state: 'Haryana',
    country: 'India',
    latitude: 28.4595,
    longitude: 77.0266,
    reliability_score: 94.8,
    avg_lead_time_days: 4,
    capacity_units_per_month: 60000,
    cost_index: 1.01,
    status: 'ACTIVE',
    risk_level: 'LOW',
    risk_factors: {
      delivery_risk: 21.0,
      geopolitical_risk: 15.0,
      financial_health_risk: 19.0,
      weather_climate_risk: 20.0,
      capacity_constraint_risk: 30.0,
      summary: 'High automated surface mount lines with multi-shift buffer.',
    },
    primary_contact: {
      name: 'Sunil Aggarwal',
      title: 'VP Supply Chain',
      email: 's.aggarwal@lumaxauto.com',
      phone: '+91 98100 99412',
    },
  },
  {
    id: 'sup-08',
    code: 'SUP-DIXON-TIR',
    name: 'Dixon Technologies Precision',
    tier: 'TIER_1',
    category: 'IoT Controllers & Smart Meters',
    city: 'Tirupati',
    state: 'Andhra Pradesh',
    country: 'India',
    latitude: 13.6288,
    longitude: 79.4192,
    reliability_score: 96.9,
    avg_lead_time_days: 5,
    capacity_units_per_month: 85000,
    cost_index: 1.03,
    status: 'ACTIVE',
    risk_level: 'LOW',
    risk_factors: {
      delivery_risk: 18.0,
      geopolitical_risk: 12.0,
      financial_health_risk: 14.0,
      weather_climate_risk: 19.0,
      capacity_constraint_risk: 25.0,
      summary: 'Excellent operational health and fast railway freight link to Chennai & Bengaluru.',
    },
    primary_contact: {
      name: 'V. Krishna Murthy',
      title: 'Plant Operations Head',
      email: 'kmurthy@dixoninfo.com',
      phone: '+91 94401 22899',
    },
  },
  {
    id: 'sup-09',
    code: 'SUP-STERL-AUR',
    name: 'Sterlite Optical Nodes',
    tier: 'TIER_2',
    category: 'Fiber Telemetry & Industrial Bus',
    city: 'Aurangabad',
    state: 'Maharashtra',
    country: 'India',
    latitude: 19.8762,
    longitude: 75.3433,
    reliability_score: 89.8,
    avg_lead_time_days: 6,
    capacity_units_per_month: 35000,
    cost_index: 1.05,
    status: 'ACTIVE',
    risk_level: 'MEDIUM',
    risk_factors: {
      delivery_risk: 40.0,
      geopolitical_risk: 18.0,
      financial_health_risk: 32.0,
      weather_climate_risk: 42.0,
      capacity_constraint_risk: 50.0,
      summary: 'Moderate vulnerability to Samruddhi Mahamarg transit bottlenecks during heavy rains.',
    },
    primary_contact: {
      name: 'Manish Joshi',
      title: 'Operations Manager',
      email: 'm.joshi@sterlitetech.com',
      phone: '+91 98220 55198',
    },
  },
  {
    id: 'sup-10',
    code: 'SUP-SUNDR-CHN',
    name: 'Sundram Precision Fasteners',
    tier: 'TIER_2',
    category: 'High-Tensile Titanium Hardware',
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 13.0827,
    longitude: 80.2707,
    reliability_score: 98.4,
    avg_lead_time_days: 3,
    capacity_units_per_month: 160000,
    cost_index: 0.96,
    status: 'ACTIVE',
    risk_level: 'LOW',
    risk_factors: {
      delivery_risk: 12.0,
      geopolitical_risk: 8.0,
      financial_health_risk: 11.0,
      weather_climate_risk: 22.0,
      capacity_constraint_risk: 18.0,
      summary: 'Industry gold standard reliability; zero recorded stockouts across past 18 months.',
    },
    primary_contact: {
      name: 'G. Swaminathan',
      title: 'Commercial Director',
      email: 'swaminathan@sundram.com',
      phone: '+91 98410 44321',
    },
  },
  {
    id: 'sup-11',
    code: 'SUP-HAVELLS-RAJ',
    name: 'Havells Industrial Switchgear',
    tier: 'TIER_2',
    category: 'Power Relays & Contactors',
    city: 'Neemrana',
    state: 'Rajasthan',
    country: 'India',
    latitude: 27.9888,
    longitude: 76.3883,
    reliability_score: 93.9,
    avg_lead_time_days: 5,
    capacity_units_per_month: 70000,
    cost_index: 1.02,
    status: 'ACTIVE',
    risk_level: 'LOW',
    risk_factors: {
      delivery_risk: 22.0,
      geopolitical_risk: 14.0,
      financial_health_risk: 18.0,
      weather_climate_risk: 15.0,
      capacity_constraint_risk: 32.0,
      summary: 'Fully integrated production plant near DMIC dedicated freight corridor.',
    },
    primary_contact: {
      name: 'Deepak Verma',
      title: 'Logistics Head',
      email: 'd.verma@havells.com',
      phone: '+91 98290 77334',
    },
  },
  {
    id: 'sup-12',
    code: 'SUP-BFORGE-PUN',
    name: 'Bharat Forge Advanced Metallurgy',
    tier: 'TIER_1',
    category: 'Precision Aluminum Enclosures',
    city: 'Pune',
    state: 'Maharashtra',
    country: 'India',
    latitude: 18.5500,
    longitude: 73.9000,
    reliability_score: 91.5,
    avg_lead_time_days: 7,
    capacity_units_per_month: 75000,
    cost_index: 1.06,
    status: 'WARNING',
    risk_level: 'HIGH',
    risk_factors: {
      delivery_risk: 65.0,
      geopolitical_risk: 15.0,
      financial_health_risk: 20.0,
      weather_climate_risk: 78.0,
      capacity_constraint_risk: 60.0,
      summary: 'Pune regional monsoon warning; access roads near Mundhwa experiencing waterlogging and slow dispatch.',
    },
    primary_contact: {
      name: 'Hemant Kulkarni',
      title: 'VP Aerospace & Defense',
      email: 'h.kulkarni@bharatforge.com',
      phone: '+91 98222 88410',
    },
  },
];

// 50+ Realistically priced and categorized products
const products = [
  { id: 'p-01', sku: 'NX-MCU-3200', name: 'NexCore 32-Bit Automotive ECU', category: 'Semiconductors', unit_cost_inr: 4250, selling_price_inr: 6800, primary_supplier_id: 'sup-01', criticality: 'MISSION_CRITICAL', lead_time_days: 4 },
  { id: 'p-02', sku: 'NX-MOS-850', name: 'Silicon Carbide Power MOSFET 1200V', category: 'Power Electronics', unit_cost_inr: 1850, selling_price_inr: 2950, primary_supplier_id: 'sup-02', criticality: 'HIGH', lead_time_days: 5 },
  { id: 'p-03', sku: 'NX-BMS-48V', name: 'Smart 48V Battery Management Module', category: 'EV Powertrain', unit_cost_inr: 9200, selling_price_inr: 14500, primary_supplier_id: 'sup-01', criticality: 'MISSION_CRITICAL', lead_time_days: 6 },
  { id: 'p-04', sku: 'NX-PCB-HD8', name: 'High-Density 8-Layer Multilayer PCB', category: 'Electronics', unit_cost_inr: 1450, selling_price_inr: 2400, primary_supplier_id: 'sup-03', criticality: 'HIGH', lead_time_days: 6 },
  { id: 'p-05', sku: 'NX-CAN-BUS', name: 'Isolated Dual-CAN Transceiver IC', category: 'Semiconductors', unit_cost_inr: 620, selling_price_inr: 1100, primary_supplier_id: 'sup-01', criticality: 'MISSION_CRITICAL', lead_time_days: 4 },
  { id: 'p-06', sku: 'NX-IOT-GATE', name: 'Telematics Edge Gateway LTE/5G', category: 'IoT Systems', unit_cost_inr: 5800, selling_price_inr: 8900, primary_supplier_id: 'sup-08', criticality: 'HIGH', lead_time_days: 5 },
  { id: 'p-07', sku: 'NX-LIPO-2170', name: 'Cylindrical Li-Ion Cell 21700 Grade A', category: 'EV Powertrain', unit_cost_inr: 320, selling_price_inr: 540, primary_supplier_id: 'sup-06', criticality: 'HIGH', lead_time_days: 8 },
  { id: 'p-08', sku: 'NX-RAD-77G', name: '77GHz ADAS Millimeter-Wave Radar', category: 'Sensors', unit_cost_inr: 12500, selling_price_inr: 19800, primary_supplier_id: 'sup-01', criticality: 'MISSION_CRITICAL', lead_time_days: 5 },
  { id: 'p-09', sku: 'NX-HARN-EV', name: 'High-Voltage Flame-Retardant Harness', category: 'Automotive Electrical', unit_cost_inr: 3400, selling_price_inr: 5200, primary_supplier_id: 'sup-05', criticality: 'HIGH', lead_time_days: 4 },
  { id: 'p-10', sku: 'NX-LED-HEAD', name: 'Matrix Adaptive Matrix LED Driver', category: 'Lighting', unit_cost_inr: 2100, selling_price_inr: 3500, primary_supplier_id: 'sup-07', criticality: 'MEDIUM', lead_time_days: 4 },
  { id: 'p-11', sku: 'NX-OPT-NODE', name: 'Rugged Fiber Optic Transceiver', category: 'Industrial Bus', unit_cost_inr: 3900, selling_price_inr: 6200, primary_supplier_id: 'sup-09', criticality: 'MEDIUM', lead_time_days: 6 },
  { id: 'p-12', sku: 'NX-FAST-M10', name: 'Grade 12.9 Aerospace Hex Bolt Set', category: 'Hardware', unit_cost_inr: 45, selling_price_inr: 85, primary_supplier_id: 'sup-10', criticality: 'LOW', lead_time_days: 3 },
  { id: 'p-13', sku: 'NX-RELAY-40A', name: 'Hermetically Sealed 40A DC Contactor', category: 'Power Electronics', unit_cost_inr: 1150, selling_price_inr: 1850, primary_supplier_id: 'sup-11', criticality: 'MEDIUM', lead_time_days: 5 },
  { id: 'p-14', sku: 'NX-ALUM-ENC', name: 'CNC Milled IP68 Inverter Enclosure', category: 'Structural', unit_cost_inr: 4800, selling_price_inr: 7600, primary_supplier_id: 'sup-12', criticality: 'HIGH', lead_time_days: 7 },
  { id: 'p-15', sku: 'NX-GYRO-6AX', name: '6-Axis IMU Inertial Navigation Sensor', category: 'Sensors', unit_cost_inr: 1750, selling_price_inr: 2800, primary_supplier_id: 'sup-04', criticality: 'HIGH', lead_time_days: 7 },
  { id: 'p-16', sku: 'NX-CURR-HALL', name: 'Hall Effect Bi-Directional Current Sensor', category: 'Sensors', unit_cost_inr: 880, selling_price_inr: 1450, primary_supplier_id: 'sup-04', criticality: 'HIGH', lead_time_days: 6 },
  { id: 'p-17', sku: 'NX-TEMP-NTC', name: 'High-Precision Surface NTC Thermistor', category: 'Sensors', unit_cost_inr: 120, selling_price_inr: 240, primary_supplier_id: 'sup-01', criticality: 'LOW', lead_time_days: 4 },
  { id: 'p-18', sku: 'NX-DSP-AI', name: 'Edge AI Neural Accelerator Chiplet', category: 'Semiconductors', unit_cost_inr: 8600, selling_price_inr: 13900, primary_supplier_id: 'sup-02', criticality: 'MISSION_CRITICAL', lead_time_days: 5 },
  { id: 'p-19', sku: 'NX-DC-CONV', name: 'High-Efficiency 400V to 12V DC-DC Converter', category: 'Power Electronics', unit_cost_inr: 6500, selling_price_inr: 10200, primary_supplier_id: 'sup-01', criticality: 'HIGH', lead_time_days: 5 },
  { id: 'p-20', sku: 'NX-DISP-OLED', name: '10.25-inch Automotive Cockpit OLED Glass', category: 'Displays', unit_cost_inr: 7400, selling_price_inr: 11800, primary_supplier_id: 'sup-03', criticality: 'MEDIUM', lead_time_days: 6 },
  // Product items 21-50 generated programmatically to fulfill 50+ requirement
  ...Array.from({ length: 32 }, (_, i) => {
    const idx = 21 + i;
    const cats = ['Semiconductors', 'Power Electronics', 'Sensors', 'Automotive Electrical', 'Hardware', 'Structural'];
    const cat = cats[i % cats.length];
    const sups = ['sup-01', 'sup-02', 'sup-03', 'sup-04', 'sup-05', 'sup-06', 'sup-07', 'sup-08', 'sup-10', 'sup-11'];
    const sup = sups[i % sups.length];
    const cost = 500 + ((idx * 270) % 6500);
    return {
      id: `p-${idx}`,
      sku: `NX-COMP-${idx * 100}`,
      name: `Industrial Component Spec-${idx} (${cat})`,
      category: cat,
      unit_cost_inr: cost,
      selling_price_inr: Math.round(cost * 1.55),
      primary_supplier_id: sup,
      criticality: idx % 3 === 0 ? 'MISSION_CRITICAL' : idx % 2 === 0 ? 'HIGH' : 'MEDIUM',
      lead_time_days: 3 + (idx % 6),
    };
  }),
];

// Alternative Suppliers mapping for quick failover
const alternativeSuppliers = [
  // When sup-01 (Tata AutoComp Pune) goes down:
  {
    product_id: 'p-01', // NX-MCU-3200
    supplier_id: 'sup-02', // Bharat Silicon BLR
    preference_rank: 1,
    lead_time_days: 5,
    unit_cost_inr: 4550, // 7% premium
    capacity_available: 28000,
    carrier_expedite: 'Blue Dart Aviation (Bengaluru - Mumbai 18h)',
  },
  {
    product_id: 'p-01',
    supplier_id: 'sup-04', // Vedanta Semicon Gujarat
    preference_rank: 2,
    lead_time_days: 7,
    unit_cost_inr: 4180,
    capacity_available: 15000,
    carrier_expedite: 'Delhivery Surface Express (Dholera - Bhiwandi 36h)',
  },
  {
    product_id: 'p-03', // NX-BMS-48V
    supplier_id: 'sup-03', // Foxconn Sriperumbudur
    preference_rank: 1,
    lead_time_days: 6,
    unit_cost_inr: 9600,
    capacity_available: 18000,
    carrier_expedite: 'SpiceXpress Cargo (Chennai - Pune 24h)',
  },
  {
    product_id: 'p-05', // NX-CAN-BUS
    supplier_id: 'sup-02', // Bharat Silicon BLR
    preference_rank: 1,
    lead_time_days: 5,
    unit_cost_inr: 660,
    capacity_available: 45000,
    carrier_expedite: 'Air India Cargo Special Flight',
  },
  {
    product_id: 'p-08', // NX-RAD-77G
    supplier_id: 'sup-04',
    preference_rank: 1,
    lead_time_days: 7,
    unit_cost_inr: 13100,
    capacity_available: 9000,
    carrier_expedite: 'Express Multi-Modal Transit',
  },
  {
    product_id: 'p-19', // NX-DC-CONV
    supplier_id: 'sup-03',
    preference_rank: 1,
    lead_time_days: 6,
    unit_cost_inr: 6800,
    capacity_available: 12000,
    carrier_expedite: 'VRL Logistics Priority Green Corridor',
  },
];

const customers = [
  {
    id: 'c-01',
    code: 'CUST-MARUTI',
    name: 'Maruti Suzuki India Ltd',
    tier: 'TIER_1_ENTERPRISE',
    sla_hours: 24,
    penalty_per_day_inr: 125000,
    city: 'Gurugram',
    state: 'Haryana',
    latitude: 28.4595,
    longitude: 77.0266,
    contact_email: 'procurement.ev@maruti.co.in',
  },
  {
    id: 'c-02',
    code: 'CUST-MAHINDRA',
    name: 'Mahindra & Mahindra Auto Division',
    tier: 'TIER_1_ENTERPRISE',
    sla_hours: 24,
    penalty_per_day_inr: 95000,
    city: 'Chakan (Pune)',
    state: 'Maharashtra',
    latitude: 18.7557,
    longitude: 73.8567,
    contact_email: 'supply.chain@mahindra.com',
  },
  {
    id: 'c-03',
    code: 'CUST-TATAMOTORS',
    name: 'Tata Motors Commercial Vehicles',
    tier: 'TIER_1_ENTERPRISE',
    sla_hours: 36,
    penalty_per_day_inr: 110000,
    city: 'Pune',
    state: 'Maharashtra',
    latitude: 18.5204,
    longitude: 73.8567,
    contact_email: 'ev-procurement@tatamotors.com',
  },
  {
    id: 'c-04',
    code: 'CUST-ATHER',
    name: 'Ather Energy Smart Mobility',
    tier: 'TIER_1_ENTERPRISE',
    sla_hours: 48,
    penalty_per_day_inr: 75000,
    city: 'Hosur / Bengaluru',
    state: 'Karnataka',
    latitude: 12.9716,
    longitude: 77.5946,
    contact_email: 'operations@atherenergy.com',
  },
  {
    id: 'c-05',
    code: 'CUST-OLA',
    name: 'Ola Electric FutureFactory',
    tier: 'TIER_1_ENTERPRISE',
    sla_hours: 48,
    penalty_per_day_inr: 85000,
    city: 'Krishnagiri',
    state: 'Tamil Nadu',
    latitude: 12.5186,
    longitude: 78.2137,
    contact_email: 'factory.procurement@olaelectric.com',
  },
  {
    id: 'c-06',
    code: 'CUST-BOSCH',
    name: 'Bosch India Mobility Solutions',
    tier: 'TIER_2_COMMERCIAL',
    sla_hours: 48,
    penalty_per_day_inr: 45000,
    city: 'Bengaluru',
    state: 'Karnataka',
    latitude: 12.9352,
    longitude: 77.6245,
    contact_email: 'india.supply@bosch.com',
  },
  {
    id: 'c-07',
    code: 'CUST-SIEMENS',
    name: 'Siemens India Industrial Automation',
    tier: 'TIER_2_COMMERCIAL',
    sla_hours: 72,
    penalty_per_day_inr: 35000,
    city: 'Kalwa (Thane)',
    state: 'Maharashtra',
    latitude: 19.2000,
    longitude: 72.9800,
    contact_email: 'procure@siemens.co.in',
  },
  {
    id: 'c-08',
    code: 'CUST-HAVELLS',
    name: 'Havells Consumer Goods Division',
    tier: 'TIER_3_STANDARD',
    sla_hours: 96,
    penalty_per_day_inr: 20000,
    city: 'Noida',
    state: 'Uttar Pradesh',
    latitude: 28.5355,
    longitude: 77.3910,
    contact_email: 'central.logistics@havells.com',
  },
  {
    id: 'c-09',
    code: 'CUST-BAJAJ',
    name: 'Bajaj Auto Chakan Division',
    tier: 'TIER_1_ENTERPRISE',
    sla_hours: 24,
    penalty_per_day_inr: 70000,
    city: 'Pune',
    state: 'Maharashtra',
    latitude: 18.7500,
    longitude: 73.8600,
    contact_email: 'vendor-ops@bajajauto.co.in',
  },
  {
    id: 'c-10',
    code: 'CUST-TITAN',
    name: 'Titan Engineering & Automation (TEAL)',
    tier: 'TIER_2_COMMERCIAL',
    sla_hours: 72,
    penalty_per_day_inr: 30000,
    city: 'Hosur',
    state: 'Tamil Nadu',
    latitude: 12.7400,
    longitude: 77.8200,
    contact_email: 'teal.logistics@titan.co.in',
  },
];

// Inventory across warehouses
const inventory = [];
// Generate realistic inventory levels
products.forEach((prod, pIdx) => {
  warehouses.forEach((wh, wIdx) => {
    // Determine stock based on warehouse size and product criticality
    const baseDailyDemand = prod.criticality === 'MISSION_CRITICAL' ? 85 : prod.criticality === 'HIGH' ? 45 : 20;
    const isAffectedByTataPune = (prod.primary_supplier_id === 'sup-01');
    
    // For affected products in Western/Southern warehouses, induce severe or at-risk stock
    let currentStock;
    let reservedStock;
    let status;
    
    if (isAffectedByTataPune) {
      if (wh.code === 'WH-BHIWANDI' || wh.code === 'WH-SRIPERUMBUDUR') {
        currentStock = Math.round(baseDailyDemand * 1.8); // only 1.8 days left!
        reservedStock = Math.round(currentStock * 0.75);
        status = 'STOCKOUT_RISK';
      } else {
        currentStock = Math.round(baseDailyDemand * 4.2);
        reservedStock = Math.round(currentStock * 0.6);
        status = 'AT_RISK';
      }
    } else {
      const daysOfStock = 12 + ((pIdx + wIdx * 3) % 18);
      currentStock = baseDailyDemand * daysOfStock;
      reservedStock = Math.round(currentStock * 0.28);
      status = daysOfStock > 15 ? 'SAFE' : 'WATCH';
    }

    const availableStock = currentStock - reservedStock;
    const reorderPoint = baseDailyDemand * (prod.lead_time_days + 3);
    const safetyStockThreshold = baseDailyDemand * 3;
    const daysRemaining = baseDailyDemand > 0 ? (currentStock / baseDailyDemand).toFixed(1) : 99;

    inventory.push({
      id: `inv-${prod.id}-${wh.id}`,
      product_id: prod.id,
      product_name: prod.name,
      product_sku: prod.sku,
      warehouse_id: wh.id,
      warehouse_name: wh.name,
      warehouse_code: wh.code,
      warehouse_city: wh.city,
      current_stock: currentStock,
      reserved_stock: reservedStock,
      available_stock: availableStock,
      safety_stock_threshold: safetyStockThreshold,
      reorder_point: reorderPoint,
      daily_demand_rate: baseDailyDemand,
      days_of_supply: parseFloat(daysRemaining),
      status: status,
      unit_cost_inr: prod.unit_cost_inr,
      revenue_at_risk_inr: status === 'STOCKOUT_RISK' ? (reservedStock * prod.selling_price_inr) : 0,
    });
  });
});

// 50+ Realistic Customer Orders
const orders = [];
const orderRiskStatuses = ['ON_TRACK', 'WATCH', 'HIGH_RISK', 'CRITICAL_DELAY'];
const orderPriorities = ['CRITICAL', 'HIGH', 'NORMAL', 'LOW'];

for (let i = 1; i <= 55; i++) {
  const cust = customers[(i - 1) % customers.length];
  const prod1 = products[(i * 3) % products.length];
  const prod2 = products[(i * 5 + 1) % products.length];
  
  const isAffected = (prod1.primary_supplier_id === 'sup-01' || prod2.primary_supplier_id === 'sup-01');
  const qty1 = 50 + ((i * 17) % 350);
  const qty2 = 30 + ((i * 23) % 200);
  const totalAmount = (qty1 * prod1.selling_price_inr) + (qty2 * prod2.selling_price_inr);
  
  let riskStatus = 'ON_TRACK';
  let priority = cust.tier === 'TIER_1_ENTERPRISE' ? (i % 2 === 0 ? 'CRITICAL' : 'HIGH') : 'NORMAL';
  let orderStatus = 'IN_TRANSIT';
  let delayHours = 0;
  let prioritizationReason = `${cust.tier} customer with ₹${cust.penalty_per_day_inr.toLocaleString('en-IN')}/day SLA penalty.`;

  if (isAffected) {
    riskStatus = (cust.tier === 'TIER_1_ENTERPRISE') ? 'CRITICAL_DELAY' : 'HIGH_RISK';
    orderStatus = 'AT_RISK';
    delayHours = 72 + ((i % 4) * 24);
    prioritizationReason = `ALERT: Critical component (${prod1.sku}) tied to shutdown at Tata AutoComp Pune. Customer SLA breach expected in 18 hrs without autonomous reroute.`;
  } else if (i % 7 === 0) {
    riskStatus = 'WATCH';
    orderStatus = 'PROCESSING';
    delayHours = 12;
  } else if (i > 45) {
    orderStatus = 'DELIVERED';
  }

  const now = new Date('2026-09-30T11:50:00Z');
  const promised = new Date(now.getTime() + (24 + (i % 5) * 24) * 3600 * 1000);
  const estimated = new Date(promised.getTime() + (delayHours * 3600 * 1000));

  orders.push({
    id: `ord-${String(i).padStart(3, '0')}`,
    order_number: `ORD-2026-${String(9000 + i)}`,
    customer_id: cust.id,
    customer_name: cust.name,
    customer_tier: cust.tier,
    customer_city: cust.city,
    items: [
      { product_id: prod1.id, name: prod1.name, sku: prod1.sku, quantity: qty1, unit_price: prod1.selling_price_inr },
      { product_id: prod2.id, name: prod2.name, sku: prod2.sku, quantity: qty2, unit_price: prod2.selling_price_inr },
    ],
    total_amount_inr: totalAmount,
    priority: priority,
    status: orderStatus,
    risk_status: riskStatus,
    promised_delivery_date: promised.toISOString(),
    estimated_delivery_date: estimated.toISOString(),
    delay_hours: delayHours,
    sla_penalty_at_risk_inr: delayHours > 0 ? Math.round((delayHours / 24) * cust.penalty_per_day_inr) : 0,
    prioritization_score: cust.tier === 'TIER_1_ENTERPRISE' ? 95 - (i % 10) : 60 - (i % 20),
    prioritization_reason: prioritizationReason,
  });
}

// 20+ Shipments on Indian Logistics Corridors with real coordinates and waypoints
const shipments = [
  {
    id: 'shp-01',
    tracking_number: 'TRK-IN-908122',
    order_id: 'ord-001',
    carrier_name: 'Blue Dart Aviation Express',
    vehicle_type: 'Cargo Boeing 737 / Dedicated Flight',
    vehicle_registration: 'VT-BDA-78',
    origin_name: 'WH-BHIWANDI (Mumbai)',
    destination_name: 'Maruti Suzuki Auto Complex (Gurugram)',
    current_latitude: 22.7196,
    current_longitude: 75.8577, // Near Indore / MP Highway corridor
    status: 'IN_TRANSIT',
    speed_kmh: 82.0,
    estimated_arrival: '2026-09-30T19:30:00Z',
    delay_hours: 0,
    cargo_temperature_celsius: 21.4,
    route_corridor: 'Mumbai-Indore-Agra-Delhi Express Corridor',
  },
  {
    id: 'shp-02',
    tracking_number: 'TRK-IN-908123',
    order_id: 'ord-002',
    carrier_name: 'Delhivery Surface Heavy',
    vehicle_type: 'Multi-Axle Container Truck',
    vehicle_registration: 'MH-12-QZ-4819',
    origin_name: 'Tata AutoComp (Pune Chakan)',
    destination_name: 'Mahindra Auto Division (Chakan)',
    current_latitude: 18.7400,
    current_longitude: 73.8400, // Stranded near Chakan waterlogged zone!
    status: 'AT_RISK',
    speed_kmh: 0.0,
    estimated_arrival: '2026-10-02T12:00:00Z',
    delay_hours: 48,
    cargo_temperature_celsius: 27.2,
    route_corridor: 'Pune Chakan MIDC Spine Road - Stranded due to flash flood',
  },
  {
    id: 'shp-03',
    tracking_number: 'TRK-IN-908124',
    order_id: 'ord-003',
    carrier_name: 'VRL Logistics Priority',
    vehicle_type: '24FT Container Vehicle',
    vehicle_registration: 'KA-01-AB-9921',
    origin_name: 'WH-WHITEFIELD (Bengaluru)',
    destination_name: 'Ather Energy Smart Labs (Hosur)',
    current_latitude: 12.8399,
    current_longitude: 77.7800, // Electronic City Elevated toll
    status: 'IN_TRANSIT',
    speed_kmh: 58.0,
    estimated_arrival: '2026-09-30T14:45:00Z',
    delay_hours: 0,
    cargo_temperature_celsius: 22.0,
    route_corridor: 'NH44 Bengaluru-Hosur Highway',
  },
  {
    id: 'shp-04',
    tracking_number: 'TRK-IN-908125',
    order_id: 'ord-004',
    carrier_name: 'Gati-KWE Multi-Modal',
    vehicle_type: 'Insulated High-Cube Trailer',
    vehicle_registration: 'TN-09-CR-3310',
    origin_name: 'Foxconn Hub (Sriperumbudur)',
    destination_name: 'WH-SHAMSHABAD (Hyderabad)',
    current_latitude: 14.4426,
    current_longitude: 79.9865, // Near Nellore
    status: 'IN_TRANSIT',
    speed_kmh: 62.0,
    estimated_arrival: '2026-10-01T04:15:00Z',
    delay_hours: 2,
    cargo_temperature_celsius: 23.5,
    route_corridor: 'NH16 Chennai-Nellore-Hyderabad Expressway',
  },
  {
    id: 'shp-05',
    tracking_number: 'TRK-IN-908126',
    order_id: 'ord-005',
    carrier_name: 'Mahindra Logistics Express',
    vehicle_type: 'GPS-Monitored Reefer Van',
    vehicle_registration: 'GJ-01-XX-7811',
    origin_name: 'Vedanta Semicon (Dholera)',
    destination_name: 'WH-BHIWANDI (Mumbai)',
    current_latitude: 21.1702,
    current_longitude: 72.8311, // Passing Surat bypass
    status: 'IN_TRANSIT',
    speed_kmh: 68.0,
    estimated_arrival: '2026-09-30T22:00:00Z',
    delay_hours: 0,
    cargo_temperature_celsius: 19.8,
    route_corridor: 'Delhi-Mumbai Industrial Corridor (DMIC Phase-1)',
  },
  // Additional shipments to populate control tower live map
  {
    id: 'shp-06',
    tracking_number: 'TRK-IN-908127',
    order_id: 'ord-006',
    carrier_name: 'Blue Dart Surface',
    vehicle_type: 'Container Truck',
    vehicle_registration: 'HR-55-TY-1044',
    origin_name: 'WH-MANESAR (Gurugram)',
    destination_name: 'Siemens Kalwa Works (Mumbai)',
    current_latitude: 25.3176,
    current_longitude: 75.6420, // Near Kota Rajasthan
    status: 'IN_TRANSIT',
    speed_kmh: 64.0,
    estimated_arrival: '2026-10-01T16:00:00Z',
    delay_hours: 0,
    cargo_temperature_celsius: 22.0,
    route_corridor: 'NH48 Golden Quadrilateral',
  },
  {
    id: 'shp-07',
    tracking_number: 'TRK-IN-908128',
    order_id: 'ord-007',
    carrier_name: 'Safexpress Logistics',
    vehicle_type: 'Trailer Truck',
    vehicle_registration: 'AP-03-MK-8820',
    origin_name: 'Dixon Tech (Tirupati)',
    destination_name: 'WH-WHITEFIELD (Bengaluru)',
    current_latitude: 13.2100,
    current_longitude: 78.5000, // Near Kolar
    status: 'IN_TRANSIT',
    speed_kmh: 52.0,
    estimated_arrival: '2026-09-30T17:00:00Z',
    delay_hours: 0,
    cargo_temperature_celsius: 24.1,
    route_corridor: 'NH75 Tirupati-Chittoor-Bengaluru',
  },
  {
    id: 'shp-08',
    tracking_number: 'TRK-IN-908129',
    order_id: 'ord-008',
    carrier_name: 'TCI Freight',
    vehicle_type: 'Covered Fleet Truck',
    vehicle_registration: 'MH-14-GH-2189',
    origin_name: 'Tata AutoComp (Pune)',
    destination_name: 'WH-WHITEFIELD (Bengaluru)',
    current_latitude: 17.6599,
    current_longitude: 74.0000, // Near Satara
    status: 'DELAYED',
    speed_kmh: 22.0,
    estimated_arrival: '2026-10-02T18:00:00Z',
    delay_hours: 36,
    cargo_temperature_celsius: 25.0,
    route_corridor: 'NH48 Pune-Satara-Kolhapur-Belgaum',
  },
  {
    id: 'shp-09',
    tracking_number: 'TRK-IN-908130',
    order_id: 'ord-009',
    carrier_name: 'Blue Dart Aviation Special',
    vehicle_type: 'Air Freight Charter',
    vehicle_registration: 'VT-BDA-91',
    origin_name: 'Bharat Silicon (Bengaluru Kempegowda)',
    destination_name: 'Chhatrapati Shivaji Terminal Cargo (Mumbai)',
    current_latitude: 15.3647,
    current_longitude: 75.1240, // Flying above Hubli
    status: 'IN_TRANSIT',
    speed_kmh: 680.0,
    estimated_arrival: '2026-09-30T13:30:00Z',
    delay_hours: 0,
    cargo_temperature_celsius: 18.5,
    route_corridor: 'Air Corridor South-West Priority Express',
  },
  {
    id: 'shp-10',
    tracking_number: 'TRK-IN-908131',
    order_id: 'ord-010',
    carrier_name: 'Delhivery Cross-Country',
    vehicle_type: 'Heavy 32FT Truck',
    vehicle_registration: 'DL-01-EE-7721',
    origin_name: 'Motherson Sumi (Noida)',
    destination_name: 'WH-MANESAR (Gurugram)',
    current_latitude: 28.4800,
    current_longitude: 77.1500,
    status: 'DELIVERED',
    speed_kmh: 0.0,
    estimated_arrival: '2026-09-30T10:15:00Z',
    delay_hours: 0,
    cargo_temperature_celsius: 22.8,
    route_corridor: 'Eastern Peripheral Expressway',
  },
  {
    id: 'shp-11',
    tracking_number: 'TRK-IN-908132',
    order_id: 'ord-011',
    carrier_name: 'CJ Darcl Logistics',
    vehicle_type: 'Semi-Trailer Heavy',
    vehicle_registration: 'RJ-14-GA-9022',
    origin_name: 'Havells (Neemrana)',
    destination_name: 'WH-SHAMSHABAD (Hyderabad)',
    current_latitude: 23.1765,
    current_longitude: 75.7885, // Passing Ujjain / Indore bypass
    status: 'IN_TRANSIT',
    speed_kmh: 56.0,
    estimated_arrival: '2026-10-02T08:00:00Z',
    delay_hours: 4,
    cargo_temperature_celsius: 23.0,
    route_corridor: 'DMIC North-South Corridor',
  },
  {
    id: 'shp-12',
    tracking_number: 'TRK-IN-908133',
    order_id: 'ord-012',
    carrier_name: 'VRL Logistics Express',
    vehicle_type: 'Multi-Axle Truck',
    vehicle_registration: 'KA-25-D-4411',
    origin_name: 'Sundram Fasteners (Chennai)',
    destination_name: 'WH-WHITEFIELD (Bengaluru)',
    current_latitude: 12.9500,
    current_longitude: 79.1300, // Near Vellore
    status: 'IN_TRANSIT',
    speed_kmh: 65.0,
    estimated_arrival: '2026-09-30T16:30:00Z',
    delay_hours: 0,
    cargo_temperature_celsius: 24.5,
    route_corridor: 'NH48 Chennai-Vellore-Bengaluru Expressway',
  },
];

// Disruption Master Scenarios (with the primary live demo disruption)
const disruptions = [
  {
    id: 'disrupt-01',
    code: 'DISRUPT-PUNE-FLOOD-01',
    title: 'Flash Flood & Substation Grid Outage at Pune Chakan Industrial Cluster',
    type: 'SUPPLIER_SHUTDOWN',
    severity: 'CRITICAL',
    status: 'ACTIVE',
    source: 'IOT_POWER_GRID_TELEMETRY',
    affected_entity_type: 'SUPPLIER',
    affected_entity_id: 'sup-01',
    affected_entity_name: 'Tata AutoComp Systems Ltd (Chakan Plant)',
    latitude: 18.7500,
    longitude: 73.8500,
    radius_km: 35,
    expected_duration_days: 5,
    estimated_loss_inr: 24500000,
    detected_at: new Date(Date.now() - 48 * 60 * 1000).toISOString(),
    details: {
      cause: 'Severe cloudburst dumped 165mm rainfall in 3 hours. Chakan MIDC 220kV substation flooded, halting cleanroom lines.',
      affected_skus: ['NX-MCU-3200', 'NX-BMS-48V', 'NX-CAN-BUS', 'NX-RAD-77G'],
      affected_order_count: 18,
      affected_revenue_inr: 38200000,
      at_risk_customers: ['Maruti Suzuki India', 'Mahindra Auto', 'Tata Motors Commercial', 'Ather Energy'],
    },
  },
  {
    id: 'disrupt-02',
    code: 'DISRUPT-CHENNAI-PORT-02',
    title: 'Port Congestion & Customs Berth Delays at Ennore & Chennai Harbour',
    type: 'PORT_CONGESTION',
    severity: 'MEDIUM',
    status: 'ACTIVE',
    source: 'PORT_AIS_VESSEL_TRACKER',
    affected_entity_type: 'ROUTE',
    affected_entity_id: null,
    affected_entity_name: 'Chennai Port Container Terminal',
    latitude: 13.0827,
    longitude: 80.2707,
    radius_km: 25,
    expected_duration_days: 3,
    estimated_loss_inr: 4200000,
    detected_at: new Date(Date.now() - 14 * 3600 * 1000).toISOString(),
    details: {
      cause: 'Berth cranes maintenance and high swell causing average container dwell time to increase from 28h to 76h.',
      affected_skus: ['NX-PCB-HD8', 'NX-DISP-OLED'],
      affected_order_count: 6,
      affected_revenue_inr: 8900000,
      at_risk_customers: ['Bosch India', 'Siemens India'],
    },
  },
  {
    id: 'disrupt-03',
    code: 'DISRUPT-HIGHWAY-NH48-03',
    title: 'Landslide Cleared on Khandala Ghat (Mumbai-Pune Expressway)',
    type: 'HIGHWAY_BLOCKAGE',
    severity: 'LOW',
    status: 'RESOLVED',
    source: 'NHAI_FASTAG_SURVEILLANCE',
    affected_entity_type: 'ROUTE',
    affected_entity_id: null,
    affected_entity_name: 'Khandala Ghat Km 84',
    latitude: 18.7600,
    longitude: 73.3700,
    radius_km: 15,
    expected_duration_days: 1,
    estimated_loss_inr: 850000,
    detected_at: new Date(Date.now() - 36 * 3600 * 1000).toISOString(),
    resolved_at: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
    details: {
      cause: 'Minor rockfall on outer lane cleared by NHAI rapid response team. Traffic flow restored to 60 km/h.',
      affected_skus: [],
      affected_order_count: 4,
      affected_revenue_inr: 2100000,
      at_risk_customers: ['Mahindra Auto'],
    },
  },
];

// Seed AI Autonomous Decisions with Candidate Options A to F
const aiDecisions = [
  {
    id: 'dec-01',
    disruption_id: 'disrupt-01',
    agent_name: 'SupplyChain Guardian v2.4 (Autonomous Multi-Criteria Engine)',
    summary: 'Autonomous Response Strategy for Tata AutoComp Chakan Shutdown: Multi-modal reroute and secondary supplier activation.',
    severity: 'CRITICAL',
    affected_orders: ['ord-001', 'ord-002', 'ord-003', 'ord-004', 'ord-005', 'ord-008', 'ord-014', 'ord-018'],
    affected_inventory: ['inv-p-01-wh-01', 'inv-p-03-wh-01', 'inv-p-05-wh-03'],
    candidate_actions: [
      {
        option_id: 'OPTION_A',
        title: 'Wait for Current Supplier Recovery (No Intervention)',
        cost_inr: 0,
        estimated_delay_hours: 120, // 5 days
        sla_penalty_inr: 12500000,
        total_financial_impact_inr: 12500000,
        risk_score: 96.0,
        pros: ['Zero immediate procurement cash outlay'],
        cons: ['Severe SLA violations across 18 customer orders', 'Line stops at Maruti & Mahindra assembly plants', 'Irreparable customer relationship damage'],
        is_recommended: false,
      },
      {
        option_id: 'OPTION_B',
        title: 'Activate Secondary Supplier (Bharat Silicon BLR) + Blue Dart Air Cargo',
        cost_inr: 1845000,
        estimated_delay_hours: 18,
        sla_penalty_inr: 180000,
        total_financial_impact_inr: 2025000,
        risk_score: 18.5,
        pros: ['Reduces delivery delay by 85%', 'Saves ₹1.04 Cr in SLA penalties and customer downtime', 'Bharat Silicon has verified buffer stock of 28,000 units in cleanroom'],
        cons: ['7% unit price premium + air freight expediting cost of ₹4,20,000'],
        is_recommended: true,
      },
      {
        option_id: 'OPTION_C',
        title: 'Split Purchase Order: 60% Bharat Silicon BLR + 40% Foxconn Sriperumbudur',
        cost_inr: 2150000,
        estimated_delay_hours: 26,
        sla_penalty_inr: 340000,
        total_financial_impact_inr: 2490000,
        risk_score: 24.0,
        pros: ['Dual-source redundancy eliminates single point of failure', 'Guarantees 100% quantity fulfillment'],
        cons: ['Higher administrative overhead with two parallel purchase orders', 'Differential lead times requiring dual receiving docks'],
        is_recommended: false,
      },
      {
        option_id: 'OPTION_D',
        title: 'Emergency Stock Transfer from WH-SHAMSHABAD (Hyderabad) via Road Express',
        cost_inr: 820000,
        estimated_delay_hours: 32,
        sla_penalty_inr: 650000,
        total_financial_impact_inr: 1470000,
        risk_score: 42.0,
        pros: ['Uses existing inventory without external supplier purchase'],
        cons: ['Depletes Deccan depot buffer below 25% safety stock threshold', 'Leaves Hyderabad region vulnerable if secondary disruption occurs'],
        is_recommended: false,
      },
      {
        option_id: 'OPTION_E',
        title: 'Ration Existing Bhiwandi Inventory & Prioritize Tier-1 Enterprise Customers',
        cost_inr: 350000,
        estimated_delay_hours: 72,
        sla_penalty_inr: 4500000,
        total_financial_impact_inr: 4850000,
        risk_score: 68.0,
        pros: ['Protects Maruti Suzuki & Mahindra contracts'],
        cons: ['Tier-2 and Tier-3 customers suffer 4-day delays and stockouts'],
        is_recommended: false,
      },
      {
        option_id: 'OPTION_F',
        title: 'Expedite Air Charter from Global Stockist (Singapore Hub)',
        cost_inr: 6500000,
        estimated_delay_hours: 14,
        sla_penalty_inr: 0,
        total_financial_impact_inr: 6500000,
        risk_score: 35.0,
        pros: ['Fastest arrival time (14 hrs)'],
        cons: ['Prohibitive cost (3.5x higher than Option B)', 'Customs clearance risk at Mumbai Air Cargo terminal'],
        is_recommended: false,
      },
    ],
    selected_action: 'OPTION_B',
    selected_action_title: 'Activate Secondary Supplier (Bharat Silicon BLR) + Blue Dart Air Cargo',
    reasoning_summary: 'Multi-criteria decision analysis (MCDA) ranks Option B optimal (Score: 94.2/100). Cost of ₹18,45,000 avoids ₹1.25 Cr in customer SLA penalties and production line halts. Bharat Silicon confirmed 28,000 unit buffer ready for immediate dispatch from Bengaluru Kempegowda hub via Blue Dart Aviation flight BDA-91.',
    estimated_cost_inr: 1845000,
    estimated_delay_hours: 18,
    risk_level: 'LOW',
    confidence_score: 95.8,
    requires_human_approval: true,
    approval_status: 'PENDING',
    approved_by: null,
    approved_at: null,
    rejection_reason: null,
    execution_status: 'PENDING',
    created_at: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    workflow_steps: [
      { step: 1, name: 'Disruption Detected', status: 'COMPLETED', time: '10:42 AM', detail: 'Chakan MIDC power outage sensor alert received' },
      { step: 2, name: 'Affected Suppliers Identified', status: 'COMPLETED', time: '10:43 AM', detail: 'Tata AutoComp Systems Ltd flagged 100% shutdown' },
      { step: 3, name: 'Affected Inventory Mapped', status: 'COMPLETED', time: '10:43 AM', detail: '4 SKUs flagged at Bhiwandi & Chennai depots' },
      { step: 4, name: 'Affected Orders Isolated', status: 'COMPLETED', time: '10:44 AM', detail: '18 customer orders identified with SLA deadline < 48 hrs' },
      { step: 5, name: 'Delivery Impact Calculated', status: 'COMPLETED', time: '10:44 AM', detail: 'Estimated average delay without intervention: 120 hrs' },
      { step: 6, name: 'Alternative Suppliers Queried', status: 'COMPLETED', time: '10:45 AM', detail: 'Bharat Silicon BLR & Foxconn Sriperumbudur qualified' },
      { step: 7, name: 'Options Evaluated', status: 'COMPLETED', time: '10:45 AM', detail: '6 candidate recovery scenarios computed (A to F)' },
      { step: 8, name: 'Cost, SLA & Risk Weighted', status: 'COMPLETED', time: '10:46 AM', detail: 'Option B achieves 85% delay reduction with minimal net cost' },
      { step: 9, name: 'Strategy Generated', status: 'COMPLETED', time: '10:46 AM', detail: 'Autonomous Purchase Order #PO-REC-901 drafted' },
      { step: 10, name: 'Business Rules Evaluated', status: 'COMPLETED', time: '10:46 AM', detail: 'Order value ₹18.45L exceeds auto-execute threshold (₹5L)' },
      { step: 11, name: 'Human Approval Required', status: 'IN_PROGRESS', time: '10:47 AM', detail: 'Dispatched approval ticket to Supply Chain Manager' },
      { step: 12, name: 'AI Decision Record Created', status: 'COMPLETED', time: '10:47 AM', detail: 'Audit record #DEC-01 created with cryptographic hash' },
      { step: 13, name: 'Execute Permitted Actions', status: 'PENDING', time: 'Pending Approval', detail: 'Pending human authorization' },
      { step: 14, name: 'Monitor Result', status: 'PENDING', time: 'Pending Execution', detail: 'Awaiting dispatch confirmation' },
      { step: 15, name: 'Update Dashboard & Model', status: 'PENDING', time: 'Pending Execution', detail: 'Real-time telemetry stream listener active' },
    ],
  },
];

// Initial Audit Logs (Demonstrating Responsible & Auditable AI)
const auditLogs = [
  {
    id: 'aud-01',
    timestamp: new Date(Date.now() - 48 * 60 * 1000).toISOString(),
    user_name: 'SupplyChain Guardian AI',
    agent_id: 'Guardian-Autonomous-Agent-01',
    event_category: 'DISRUPTION_TRIGGER',
    event_name: 'Disruption Incident Registered',
    input_context_summary: 'Automated telemetry ingestion detected total electrical loss at Chakan Substation #4.',
    decision_summary: 'Disruption #DISRUPT-PUNE-FLOOD-01 logged with severity CRITICAL. Triggered automated impact assessment.',
    action_taken: 'Isolated all active shipments originating from Tata AutoComp Pune. Notified operations room.',
    approval_status: 'AUTO_EXECUTED',
    result_status: 'SUCCESS',
    details: { event_source: 'MQTT_TELEMETRY', incident_code: 'DISRUPT-PUNE-FLOOD-01' },
  },
  {
    id: 'aud-02',
    timestamp: new Date(Date.now() - 44 * 60 * 1000).toISOString(),
    user_name: 'SupplyChain Guardian AI',
    agent_id: 'Guardian-Autonomous-Agent-01',
    event_category: 'AI_DECISION',
    event_name: 'Autonomous MCDA Multi-Option Optimization',
    input_context_summary: 'Evaluated 18 affected customer orders, 3 warehouses, and 3 alternative semiconductor foundries.',
    decision_summary: 'Generated 6 candidate strategies (Options A-F). Recommended Option B (Bharat Silicon BLR + Blue Dart Air).',
    action_taken: 'Drafted PO-REC-901 for ₹18,45,000 and reserved air cargo slot on Flight BDA-91.',
    approval_status: 'PENDING',
    result_status: 'SUCCESS',
    details: { options_evaluated: 6, best_option: 'OPTION_B', cost_inr: 1845000, penalty_avoided_inr: 10475000 },
  },
  {
    id: 'aud-03',
    timestamp: new Date(Date.now() - 25 * 3600 * 1000).toISOString(),
    user_name: 'Ananya Sharma (Supply Manager)',
    agent_id: 'Guardian-Autonomous-Agent-01',
    event_category: 'HUMAN_APPROVAL',
    event_name: 'Historical Action Approved: Route Diversion',
    input_context_summary: 'Khandala Ghat landslide diversion request for 4 container trucks via Kasara route.',
    decision_summary: 'Manager approved route diversion recommendation within 3 minutes of alert generation.',
    action_taken: 'Telemetry waypoints updated in vehicle onboard units. Shipments delivered with zero SLA breach.',
    approval_status: 'APPROVED',
    result_status: 'SUCCESS',
    details: { approved_action: 'REROUTE_VIA_KASARA_GHAT', additional_toll_inr: 18000 },
  },
];

// Initial Notifications
const notifications = [
  {
    id: 'notif-01',
    title: 'CRITICAL DISRUPTION: Pune Chakan Plant Down',
    message: 'Flash flooding at Tata AutoComp halted microcontroller production. 18 customer orders at immediate risk.',
    type: 'CRITICAL',
    severity: 'HIGH',
    link: '/decisions',
    is_read: false,
    created_at: new Date(Date.now() - 47 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-02',
    title: 'AI ACTION APPROVAL REQUIRED (₹18,45,000)',
    message: 'SupplyChain Guardian recommends activating Bharat Silicon BLR to recover 18 orders. Action exceeds auto-threshold.',
    type: 'APPROVAL_REQUIRED',
    severity: 'HIGH',
    link: '/decisions',
    is_read: false,
    created_at: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-03',
    title: 'Low Stockout Warning: NX-MCU-3200',
    message: 'Bhiwandi Mega DC available inventory has dropped below 2 days of supply.',
    type: 'WARNING',
    severity: 'MEDIUM',
    link: '/inventory',
    is_read: false,
    created_at: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-04',
    title: 'Ennore Port Congestion Alert',
    message: 'Average customs container dwell time increased to 76h. Consider inland road transport buffer.',
    type: 'INFO',
    severity: 'LOW',
    link: '/tracking',
    is_read: true,
    created_at: new Date(Date.now() - 14 * 3600 * 1000).toISOString(),
  },
];

module.exports = {
  users,
  warehouses,
  suppliers,
  products,
  alternativeSuppliers,
  customers,
  inventory,
  orders,
  shipments,
  disruptions,
  aiDecisions,
  auditLogs,
  notifications,
};
