module.exports = {
  ROLES: {
    ADMIN: 'ADMIN',
    SUPPLY_MANAGER: 'SUPPLY_MANAGER',
    OPERATIONS_MANAGER: 'OPERATIONS_MANAGER',
    VIEWER: 'VIEWER',
  },
  DISRUPTION_TYPES: {
    SUPPLIER_SHUTDOWN: 'SUPPLIER_SHUTDOWN',
    SUPPLIER_DELAY: 'SUPPLIER_DELAY',
    WAREHOUSE_FAILURE: 'WAREHOUSE_FAILURE',
    PORT_CLOSURE: 'PORT_CLOSURE',
    PORT_CONGESTION: 'PORT_CONGESTION',
    TRANSPORTATION_DELAY: 'TRANSPORTATION_DELAY',
    DEMAND_SPIKE: 'DEMAND_SPIKE',
    INVENTORY_SHORTAGE: 'INVENTORY_SHORTAGE',
    VEHICLE_FAILURE: 'VEHICLE_FAILURE',
    WEATHER_CYCLONE: 'WEATHER_CYCLONE',
  },
  SEVERITY_LEVELS: {
    CRITICAL: 'CRITICAL',
    HIGH: 'HIGH',
    MEDIUM: 'MEDIUM',
    LOW: 'LOW',
  },
  AUTONOMOUS_MODES: {
    AUTONOMOUS: 'AUTONOMOUS',      // Low-risk auto-executed; threshold configurable
    ASSISTED: 'ASSISTED',          // Requires 1-click human verification
    MANUAL_APPROVAL: 'MANUAL_APPROVAL', // All actions require manager signature
  },
  AUTO_APPROVAL_THRESHOLD_INR: 500000, // ₹5,00,000 threshold for automated execution
};
